export declare function scf_handler(): any;
export declare function fc_handler(): any;
export declare function cfc_handler(): any;
export declare function qinglong(): void;
export declare function run(): void;
export declare function sacnLogin(): Promise<void>;
export declare function runInputTasks(task: string): void;
export declare const agc_handler: typeof cfc_handler;
export declare const fg_handler: typeof cfc_handler;
export declare const ql: typeof qinglong;
export default run;
